name: bridge
description: Extensible end-to-end framework
author: Emil Persson <emil.n.persson@gmail.com>
version: 0.1.0
dependencies:
  vue: ">=0.1.0 <1.0.0"
  cupid: ">=0.3.0 <0.4.0"
  shelf: ">=0.6.1+2 <0.7.0"
  shelf_static: ">=0.2.2 <0.3.0"
  yaml: ">=2.1.2 <3.0.0"
  objectory: ">=0.3.22 <0.4.0"