name: bridge
description: Extensible end-to-end framework
author: Emil Persson <emil.n.persson@gmail.com>
version: 0.3.5
homepage: http://github.com/dart-bridge/framework
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  shelf: ">=0.6.1+2 <0.7.0"
  shelf_static: ">=0.2.2 <0.3.0"
  yaml: ">=2.1.2 <3.0.0"
  cupid: ">=0.5.5 <1.0.0"
  dotenv: "^0.1.3+1"
  shelf_web_socket: '^0.0.1+2'
  http_parser: '^0.0.2+6'
  formler: any
  mustache: '^0.2.3'
  mongo_dart: '^0.1.47'
dev_dependencies:
  test: any
  testcase: ">=0.1.0 <1.0.0"
