name: bridge
description: Extensible end-to-end framework
author: Emil Persson <emil.n.persson@gmail.com>
version: 0.2.1
homepage: http://github.com/emilniklas/dart-bridge
dependencies:
  shelf: ">=0.6.1+2 <0.7.0"
  shelf_static: ">=0.2.2 <0.3.0"
  yaml: ">=2.1.2 <3.0.0"
  cupid: ">=0.5.2 <1.0.0"
dev_dependencies:
  test: any
  testcase: ">=0.1.0 <1.0.0"
